site_name: Testing

docs_dir: .
site_dir: site
repo_url: https://github.com/oliversheridanmethven/testing

use_directory_urls: false
# Because we use the `README.md` convention rather than
# the `index.md` convention, this ensures hyperlinks resolve
# correctly.

#theme:
#  name: material
#  features:
#    - toc.integrate
#
##theme: readthedocs
#markdown_extensions:
#  - admonition # Gives nice highlight fields.
#  - toc:
#      permalink: true
#  - toc:
#      title: Contents

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/oliversheridanmethven/testing
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/oliver-sheridan-methven/
    - icon: fontawesome/solid/envelope
      link: mailto:oliver.sheridan-methven@hotmail.co.uk

plugins:
  - search
  - social
  - exclude:
      glob:
        - venv/*
        - "*license.html"
        - "*LICENSE.html"
        - _skbuild/*
  - same-dir # Allows us to operate from the root directory.
  - awesome-pages:
      collapse_single_pages: true
