site_name: Testing

docs_dir: .
site_dir: site
repo_url: https://github.com/oliversheridanmethven/testing

use_directory_urls: false
# Because we use the `README.md` convention rather than
# the `index.md` convention, this ensures hyperlinks resolve
# correctly.

theme: readthedocs
markdown_extensions:
  - admonition # Gives nice highlight fields.

plugins:
  - search
  - exclude:
      glob:
        - venv/*
        - "*license.html"
        - "*LICENSE.html"
        - _skbuild/*
  - same-dir # Allows us to operate from the root directory.
  - awesome-pages:
      collapse_single_pages: true
